#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const srcDir = path.resolve(
  __dirname,
  '../../Source Data/d6holocron/starships'
);
const outDir = path.resolve(__dirname);

const files = [
  'starfighters-import-ready.json',
  'transports-import-ready.json',
  'capital-import-ready.json',
];

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function sqlEscapeString(s) {
  if (s === null || s === undefined) return 'NULL';
  return "'" + String(s).replace(/'/g, "''") + "'";
}

function jsonSql(v) {
  if (v === null || v === undefined) return 'NULL';
  return sqlEscapeString(JSON.stringify(v));
}

function writeHeader(filePath) {
  fs.writeFileSync(filePath, '-- Generated by import_starships.js\n\n', 'utf8');
}

for (const f of files) {
  const input = path.join(srcDir, f);
  if (!fs.existsSync(input)) {
    console.warn('Missing file, skipping:', input);
    continue;
  }

  const raw = fs.readFileSync(input, 'utf8');
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    console.error('JSON parse failed for', input);
    continue;
  }

  const items = parsed.starships || parsed.items || [];
  const outFile = path.join(outDir, f.replace('-import-ready.json', '.sql'));
  writeHeader(outFile);

  for (const item of items) {
    const slug = slugify(
      item.name || item.craft || (item.pageId || Math.random()).toString()
    );
    const name = sqlEscapeString(item.name || '');
    const craft = sqlEscapeString(item.craft || null);
    const affiliation = sqlEscapeString(item.affiliation || null);
    const type = sqlEscapeString(item.type || null);
    const category = sqlEscapeString(item.category || null);
    const scale = sqlEscapeString(item.scale || null);
    const length = sqlEscapeString(item.length || null);
    const skill = sqlEscapeString(item.skill || null);
    const crew = sqlEscapeString(item.crew || null);
    const crewSkill = sqlEscapeString(item.crewSkill || null);
    const passengers = sqlEscapeString(item.passengers || null);
    const cargoCapacity = sqlEscapeString(item.cargoCapacity || null);
    const consumables = sqlEscapeString(item.consumables || null);
    const cost = sqlEscapeString(item.cost || null);
    const hyperdrive = sqlEscapeString(item.hyperdrive || null);
    const navComputer = sqlEscapeString(item.navComputer || null);
    const maneuverability = sqlEscapeString(item.maneuverability || null);
    const space = sqlEscapeString(item.space || null);
    const atmosphere = sqlEscapeString(item.atmosphere || null);
    const hull = sqlEscapeString(item.hull || null);
    const shields = sqlEscapeString(item.shields || null);
    const sensors = jsonSql(item.sensors || null);
    const weapons = jsonSql(item.weapons || null);
    const description = sqlEscapeString(item.description || null);
    const imageFilename = sqlEscapeString(item.imageFilename || null);
    const imageUrl = sqlEscapeString(item.imageUrl || null);
    const notes = sqlEscapeString(item.notes || null);
    const sources = jsonSql(item.sources || null);
    const pageId = item.pageId ? Number(item.pageId) : 'NULL';
    const revisionId = item.revisionId ? Number(item.revisionId) : 'NULL';

    const insert = `REPLACE INTO starships (slug,name,craft,affiliation,type,category,scale,length,skill,crew,crewSkill,passengers,cargoCapacity,consumables,cost,hyperdrive,navComputer,maneuverability,space,atmosphere,hull,shields,sensors,weapons,description,imageFilename,imageUrl,notes,sources,pageId,revisionId) VALUES (${sqlEscapeString(slug)},${name},${craft},${affiliation},${type},${category},${scale},${length},${skill},${crew},${crewSkill},${passengers},${cargoCapacity},${consumables},${cost},${hyperdrive},${navComputer},${maneuverability},${space},${atmosphere},${hull},${shields},${sensors},${weapons},${description},${imageFilename},${imageUrl},${notes},${sources},${pageId},${revisionId});\n`;

    fs.appendFileSync(outFile, insert, 'utf8');
  }

  console.log('Wrote', outFile, 'with', items.length, 'rows');
}

console.log('Done');
